version: "3.4"

services:


  springbootdocker:
    build: .
    image: iss-spy-app
    container_name: iss-spy-app
    ports:
    - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
